### ISSUE TITLE
Fuzzy search via search endpoint

### ISSUE THREAD

**Issue by pe1uca** [goniszewski/grimoire#104]
**Is your feature request related to a problem? Please describe.**  
I'd like to integrate grimoire with some search engines and search functionality of some apps via API.  

**Describe the solution you'd like**  
Implement a `search_term` parameter to have the exact same fuzzy search fuse.js provides to the UI.  

A quicker option would be to make the `url` parameter do a fuzzy search instead of an exact one.  
https://github.com/goniszewski/grimoire/blob/7f92c7eb4f06cb1e6df150e542c4934e3cb3dd04/src/routes/api/bookmarks/%2Bserver.ts#L125-L128  

**Describe alternatives you've considered**
- Leave the functionality to each service to pull the data and implement the search.  

**Additional context**
https://docs.searxng.org/_modules/searx/engines/demo_online.html#request

**Comment by goniszewski** [comment]
Hello @pe1uca! Thank you for this great issue - it is very helpful, and I appreciate the additional details you provided.

I would like to keep Grimoire open to integration with external services, so this is a very good candidate to do so :)

**Comment by goniszewski** [comment]
Thank you for your contribution @pe1uca!

Your changes should be in `latest` in about ~30 mins. Nicely done!
