### ISSUE TITLE
Grimoire API is not reachable!

### ISSUE THREAD

**Issue by RowanBee** [goniszewski/grimoire#113]
**Describe the bug**
When I try and use the extension, it always says "Grimoire API is not reachable!". If I try on the computer it's being hosted on, there's no issue, but on another computer on the network I can't use the extension.

**To Reproduce**
1. Go to extension
2. Click on extension

**Expected behavior**
I should be able to be greeted with a login menu, then login and use the extension.

**Screenshots**
![image](https://github.com/user-attachments/assets/07aca6ee-758a-4d50-9031-4e1ccfac3716)

**Desktop (please complete the following information):**
 - OS: NixOS
 - Firefox
 - 128.0.3

Edit: it works on chrome, just not firefox.

**Comment by abunavas** [comment]
Same problem, Firefox

**Comment by goniszewski** [comment]
Please upgrade to the latest version of Grimoire. You can use the integrated [migration tool](https://grimoire.pro/docs/migration-tool/) to transfer your data to new format.
