### ISSUE TITLE
Issues with develop branch

### ISSUE THREAD

**Issue by reallemon** [goniszewski/grimoire#118]
**Describe the bug**
I was having issues with #109 preventing me from using the release branch. As a result, I needed to try out the development branch. I have run into several issues immediately upon trying it that have kept me from trying out this application. As they all seem related or minor (and to avoid clogging the issues list about a development branch), I am just grouping them in one issue instead of making issues for each.
Issues I've found: 
1. Logging in on a fresh instance doesn't seem to work. This is notable when the container needs to be recreated. I think the error might be coming from trying to log in when there are no users and recreating the container deletes existing users, but I'm not sure. 
2. Bookmarking a site seems to fail if there is no favicon or if the app doesn't like the favicon
3. I've had some sites fail because they have an invalid URL.

**To Reproduce**
All of the following steps were taken to initialize my instance of Grimoire. I'll go over other steps as necessary for the specific issues I've listed:
1. Clone the github repository
2. Checkout the develop branch
3. Change the docker-compose file to use the develop tag instead of the latest tag 
4. Run docker compose up 

**Expected behavior**
I should be able to log in and add bookmarks.

**Desktop:**
This is what I'm using to access the web interface and what I'm using the extension on
 - OS: MacOS
 - Browser: Edge
 - Version: 128.0.2739.67

**Additional context**
I'm running the docker version of the program on a Synology NAS. 

### Logging in
When trying to log in after recreating the container, I get told I'm using invalid credentials and get this error:
```
grimoire  | 2024-09-09T20:44:53.460609538Z 420 |       e
grimoire  | 2024-09-09T20:44:53.461038738Z 421 |     );
grimoire  | 2024-09-09T20:44:53.461102663Z 422 |     if ("path" in error) {
grimoire  | 2024-09-09T20:44:53.461164725Z 423 |       let message = `Data returned from action inside ${route_id} is not serializable: ${error.message}`;
grimoire  | 2024-09-09T20:44:53.461229390Z 424 |       if (error.path !== "") message += ` (data.${error.path})`;
grimoire  | 2024-09-09T20:44:53.461286961Z 425 |       throw new Error(message);
grimoire  | 2024-09-09T20:44:53.461366833Z                   ^
grimoire  | 2024-09-09T20:44:53.461411352Z error: Data returned from action inside /login is not serializable: Cannot stringify arbitrary non-POJOs
grimoire  | 2024-09-09T20:44:53.461471066Z       at try_deserialize (/usr/src/app/build/server/index.js:425:13)
grimoire  | 2024-09-09T20:44:53.461525153Z       at /usr/src/app/build/server/index.js:1362:27
grimoire  | 2024-09-09T20:44:53.461567478Z
```
I think that this is because the user gets deleted on recreation, because I'm able to recreate the same user with the same details and then log in with that. I lose any bookmarks I had saved though

### Favicon issues
When I try to add a bookmark to [wordplayer.com](http://wordplayer.com/), I get this error when using the extension:
```
grimoire  | 2024-09-09T21:09:09.431530860Z Error creating bookmark from API request undefined is not an object (evaluating 'urlMetadataMetadata?.favicons?.[0].href')
```

And this error when using the web interface:
```
grimoire  | 2024-09-09T21:12:37.637270400Z Fetching metadata for URL http://wordplayer.com/
grimoire  | 2024-09-09T21:12:38.554616951Z 66 |     url: urlMetadataMetadata?.url || urlMetadataMetadata?.["og:url"],
grimoire  | 2024-09-09T21:12:38.554874460Z 67 |     title: urlMetadataMetadata?.title || urlMetadataMetadata?.["og:title"],
grimoire  | 2024-09-09T21:12:38.554957345Z 68 |     description: urlMetadataMetadata?.description || urlMetadataMetadata?.["og:description"],
grimoire  | 2024-09-09T21:12:38.555036353Z 69 |     author: urlMetadataMetadata?.author || urlMetadataMetadata?.["twitter:creator"],
grimoire  | 2024-09-09T21:12:38.555102856Z 70 |     mainImageUrl: urlMetadataMetadata?.image || urlMetadataMetadata?.["og:image"],
grimoire  | 2024-09-09T21:12:38.555172428Z 71 |     iconUrl: getIconUrl(url, iconUrls[0] || urlMetadataMetadata?.favicons?.[0].href)
grimoire  | 2024-09-09T21:12:38.555239335Z                                                                                  ^
grimoire  | 2024-09-09T21:12:38.555303689Z TypeError: undefined is not an object (evaluating 'urlMetadataMetadata?.favicons?.[0].href')
grimoire  | 2024-09-09T21:12:38.555374145Z       at /usr/src/app/build/server/chunks/get-metadata.js:71:77
```

### Invalid URL
When I tried to bookmark a code snippet from [playcode.io](https://playcode.io/939076), I got this error when using the extension:
```
grimoire  | 2024-09-09T21:10:35.644667391Z Error creating bookmark from API request Invalid URL
```

The web interface doesn't give me any errors and it grabs all the metadata correctly according to the logs, but it doesn't display the metadata or give me the option to actually add the bookmark despite that.

**Comment by goniszewski** [comment]
Hello @reallemon - thank you for your input. It’s truly appreciated!

I'll investigate this as soon as possible and update you on my progress with the fixes. Stay tuned!

**Comment by goniszewski** [comment]
As for the below:
> I think the error might be coming from trying to log in when there are no users and recreating the container deletes existing users, but I'm not sure.

In the `docker-compose.yml` file, we're mapping a volume to store the database and user files (currently only images). Have you created the volume and attached it to the `/app/data` directory inside the container?

**Comment by reallemon** [comment]
> In the `docker-compose.yml` file, we're mapping a volume to store the database and user files (currently only images). Have you created the volume and attached it to the `/app/data` directory inside the container?

Yeah, I've got that volume created and attached.

**Comment by goniszewski** [comment]
@reallemon I've spotted an issue with an invalid path being used in Dockerfile - it's fixed now and volume will work for `/app/data` path.

Also, there was a bug in the sign-in form, and it was resolved. Please check https://github.com/goniszewski/grimoire/releases/tag/v0.4.0-pre.3 for the updated version.
