### ISSUE TITLE
SQLiteError with version 0.4

### ISSUE THREAD

**Issue by crazybob1215** [goniszewski/grimoire#125]
**Describe the bug**
After updating to 0.4, I can't access the app. I'm getting an error `SQLiteError: no such table: `user` and an HTTP 500 anytime I try to access the app.

**To Reproduce**
1. Go to deploy using the new docker-compose example as a base.
2. Attempt to load myhost:5173
3. HTTP 500 and SQLiteError

**Expected behavior**
Expect to see the Grimoire login page.

**Compose File**

> services:
  grimoire:
    image: goniszewski/grimoire:0.4.0
    container_name: grimoire
    restart: unless-stopped
    environment:
      - PORT=5173
      - PUBLIC_HTTPS_ONLY=false
      - PUBLIC_SIGNUP_DISABLED=true
    volumes:
      - /opt/stacks/grimoire/grimoire_data:/app/data/
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$PORT/api/health ||
        exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '${PORT:-5173}:${PORT:-5173}'
networks: {}

**Container Output**
> grimoire  | Configuration used {
grimoire  |   IS_DEV: false,
grimoire  |   ORIGIN: "http://localhost:5173",
grimoire  |   HTTPS_ONLY: false,
grimoire  |   SIGNUP_DISABLED: true,
grimoire  | }
grimoire  | Listening on 0.0.0.0:5173
grimoire  | 15 |   logger;
grimoire  | 16 |   exec(query) {
grimoire  | 17 |     this.client.exec(query);
grimoire  | 18 |   }
grimoire  | 19 |   prepareQuery(query, fields, executeMethod, isResponseInArrayMode, customResultMapper) {
grimoire  | 20 |     const stmt = this.client.prepare(query.sql);
grimoire  |                                   ^
grimoire  | SQLiteError: no such table: user
grimoire  |  errno: 1
grimoire  | 
grimoire  |       at prepare (bun:sqlite:280:10)
grimoire  |       at prepareQuery (/app/node_modules/drizzle-orm/bun-sqlite/session.js:20:30)
grimoire  |       at _prepare (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:572:73)
grimoire  |       at all (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:588:17)
grimoire  |       at execute (/app/node_modules/drizzle-orm/sqlite-core/query-builders/select.js:596:19)
grimoire  |       at then (/app/node_modules/drizzle-orm/query-promise.js:21:17)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 130.0.1

**Additional context**

**Comment by zoharxero** [comment]
Getting the same error (SQLiteError: no such table: user) on a new installation.

**Comment by goniszewski** [comment]
Hello @crazybob1215, thank you for creating this issue!

Though I had fixed this a while ago, when this version was still in preview, but maybe there's more to it. Will let you know here when I came back with the solution for it.

**Comment by Chaer628** [comment]
I also have this Error on new Docker install.

Tested Tags: Latest, 0.4.0-pre.4, Develop

Changing Tag to 0.3.5 provided expected account creation page.

**Comment by goniszewski** [comment]
Fix that resolved this issue during my testing is now live https://github.com/goniszewski/grimoire/releases/tag/v0.4.1

Please let me know if the DB error still persists. Make sure to remove the previous Docker volume (if any).

**Comment by crazybob1215** [comment]
Just gave 0.4.1 a go and I'm getting a new error.

> grimoire  | $ bun run ./src/lib/database/migrate
grimoire  | error: Module not found "./src/lib/database/migrate"
grimoire  | 
grimoire  | Bun v1.1.29 (Linux x64 baseline)
grimoire  | error: script "run-migrations" exited with code 1

I deleted the files in the grimoire volume I had created before pulling, so this should be a totally fresh start.

**Comment by goniszewski** [comment]
I have made a mess of `Dockerfile` at some point, so there's the https://github.com/goniszewski/grimoire/releases/tag/v0.4.1-hotfix.2 to resolve this. Sorry for your trouble!

**Comment by crazybob1215** [comment]
Sorry to be such a pain, but hotfix 2 is still resulting in an error for me. 

>grimoire  | $ bun run ./migrate
grimoire  | 1 | import { Database } from 'bun:sqlite';
grimoire  | 2 | import { drizzle } from 'drizzle-orm/bun-sqlite';
grimoire  | 3 | import { migrate } from 'drizzle-orm/bun-sqlite/migrator';
grimoire  | 4 | 
grimoire  | 5 | const sqlite = new Database('data/db.sqlite');
grimoire  |                    ^
grimoire  | SQLiteError: unable to open database file
grimoire  |  errno: 14
grimoire  |   code: "SQLITE_CANTOPEN"
grimoire  | 
grimoire  |       at new Database (bun:sqlite:178:14)
grimoire  |       at /app/migrate.js:5:16
grimoire  | 
grimoire  | Bun v1.1.29 (Linux x64 baseline)
grimoire  | error: script "run-migrations" exited with code 1
grimoire exited with code 0

**Comment by goniszewski** [comment]
@crazybob1215, no worries! Maybe a silly question on my part, but did you try to remove the volume altogether before running the second hotfix? Looks like different directory/file permissions are the problem.

**Comment by crazybob1215** [comment]
I did completely remove the volume, but you were correct that it was a permission issue. The grimoire_data folder was being created with 755 / rwxr-xr-x permissions, so I changed it to a 777. It's working now, so I'll have to narrow down where the container is inheriting permissions from, or modify the folder permissions so it's actually owned by the container's group.

**Comment by goniszewski** [comment]
Great that you found out how to resolve this issue. 

In the current Dockerfile the `/app/data` directory is being set to `grimoire:grimoire` with `755` chroot and it worked just fine during my trials. But maybe it could be improved somehow?

If you find something that may help, please let me know!

**Comment by crazybob1215** [comment]
Got past that issue, just to run into another 🤦🏼‍♂️ See #127
