### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by DeathGabox** [goniszewski/grimoire#126]
**Describe the bug**
Getting "Illegal instruccion (core dumped)" when i try to start docker container

**To Reproduce**
1. Deploy "docker-compose.yaml" in old cpu (x86-64-v1)
2. See "container logs"

container logs
```
Container started
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Container stopped
Container stopped
Container started
Illegal instruction (core dumped)
Container stopped
```

**Expected behavior**
Run without problems

**Desktop:**
 - OS: Archlinux
 - CPU: AMD Turion II Neo N40L (1.5Ghz) K625
 - PC: HP Microserver N40L Gen7
 - Docker tag image: latest
 - Docker tag version: 0.4.1-hotfix.2

**Additional context**
- [mysql related issue](https://github.com/docker-library/mysql/issues/1055): Using latest mysql failed because need a newest set of instructions (x86-64-v2).
- [bun related issue](https://github.com/oven-sh/bun/issues/67): As i see, AVX2 is the minimal instruction set

**Possible Workarround**
Intel CPU can be emulated using [intel-sde](https://www.intel.com/content/www/us/en/download/684897/intel-software-development-emulator.html)
Mentioned in the followed bun issue
- [bun issue 181(comments)](https://github.com/oven-sh/bun/issues/181#issuecomment-1177133633)
- [bun issue 282(comments)](https://github.com/oven-sh/bun/issues/282#issuecomment-1179442791): intel-sde slow down all process

---
PD: [bun](https://bun.sh/) need a cpu with AVX2 support(x86-64-v2), any cpu newer than 2013 fit this. I think is a good idea to take note in [documentation](https://grimoire.pro/docs/getting-started/quick-start#prerequisites). This will help people with older setups.

Edit: (PD2 problem is solved with v0.4.1-hotfix.1)
PD2: I tried in my laptop (x86-64-v3) and can work :D

**Comment by goniszewski** [comment]
Hello @DeathGabox!  I guess I'm not great with these "big" releases. Always something that needs fixing right away!

Glad it started to work for you. https://github.com/goniszewski/grimoire/releases/tag/v0.4.1-hotfix.2 provides also some crucial fixes for the initial deploy of the app.

**Comment by DeathGabox** [comment]
I am going to close this issue as solved because is not a problem with grimoire but bun
This cannot be solved until bun are interest in his [Roadmap](https://github.com/oven-sh/bun/issues/159) or [Priorities](https://github.com/oven-sh/bun/issues/798)

If you encounter this in deploy, **update your CPU** to any with support to instruction x86-64-v3 (AVX / AVX2)


To view you cpu instructions
**Linux**
1. Use `grep avx2 /proc/cpuinfo`
This command extract the flag from "/proc/cpuinfo" in your cpu, if you get blank as output, you dont support avx2
> Example: Success
```
❯ grep avx2 /proc/cpuinfo
flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp vnmi md_clear flush_l1d arch_capabilities
```
> Example: Failed
```
❯ grep avx2 /proc/cpuinfo
❯ [1]> 
```
2. Use `/usr/lib/ld-linux-x86-64.so.2 --help`
This command help to see if your libraries are detected
> Example: Success
```
...
output ommited
...
Subdirectories of glibc-hwcaps directories, in priority order:
  x86-64-v4
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)
```
> Example: Failed
```
...
output ommited
...
Subdirectories of glibc-hwcaps directories, in priority order:
  x86-64-v4
  x86-64-v3
  x86-64-v2
```

**Windows**
1. You can see your cpu instructions with [cpu-z](https://www.cpuid.com/softwares/cpu-z.html)

---
Thanks goniszewski for this repo and hard work in open source and solve issues, its a awesome tool ^^
Happy Bookmark Everyone!
