### ISSUE TITLE
0.4 Migration Tool Fails

### ISSUE THREAD

**Issue by crazybob1215** [goniszewski/grimoire#127]
**Describe the bug**
The migration tool fails to import the pocketbase database and if I try to create the first user instead, nothing happens.

**To Reproduce**
1. Create the grimoire container 
2. Go to http://myhost:5173
3. Click on the migration tool link on the welcome page
4. Select my existing backup file
5. Click "Start Migration using PocketBase"
6. See error 
> Error: {"message":"Internal Error"}

and the below screenshot in the container logs

**Expected behavior**
The pocketbase export should be imported and I should be able to login with an existing account.

**Screenshots**
Docker compose contents:
![image](https://github.com/user-attachments/assets/cf055433-2b54-496c-b33d-fef1ae67cdcd)

The error when importing the pocketbase export
![image](https://github.com/user-attachments/assets/d14e1b6b-c88b-4822-89dd-d87a486a7c61)

**Additional context**
I've tried completely wiping out the container and the volume, and when that's failed a couple times I tried just starting from scratch by creating a new admin user, but that fails too. When I try to create a new first user, I don't get any errors, but nothing happens and I can't login with the credentials I just set.

**Comment by goniszewski** [comment]
Fixed in https://github.com/goniszewski/grimoire/releases/tag/v0.4.1-hotfix.3
