### ISSUE TITLE
Docker install is very cumbersome

### ISSUE THREAD

**Issue by ItsNoted** [goniszewski/grimoire#14]
It took 11 plus minutes to deploy the container only to find out it won't work locally. Do I HAVE to have it behind a reverse proxy? If so please let me know so I can test again. I hope to use this and write a review soon.

Issues seem to be with Pocketbase? When I try to log in I get this error. I followed your install guide which seems pretty basic. The install however took forever lol.

**Cross-site POST form submissions are forbidden**

![chrome_USdVWDG5KN](https://github.com/goniszewski/grimoire/assets/57927413/186ca66e-cfeb-430f-bc98-1a652934aa35)

Thank you!

**Comment by tekeous** [comment]
Duplicate of https://github.com/goniszewski/grimoire/issues/12

**Comment by goniszewski** [comment]
@ItsNoted no, you shouldn't be forced to use a reverse proxy. The missing ability to specify your designated domain name is an oversight on my side and will be fixed ASAP. This might also be related to the _Cross-site POST form_ error you mentioned, but I need to make sure.

**Comment by Famku** [comment]
I have the same issue, even with v0.1.4
Is this already fixed?

**Comment by goniszewski** [comment]
Hello @Famku! What issue do you have in mind exactly, the one with error _Cross-site POST form submissions are forbidden_?

If so, please values set in `.env` file for `PUBLIC_POCKETBASE_URL` and `ORIGIN`. You can also set `PUBLIC_HTTPS_ONLY` to `false` if there's some issue with PB cookies.

**Comment by Famku** [comment]
Hi,

I tried this, but why is the pocketbase container still unhealthy?

If I use my public domain, what are the exactly entries in the .env file?

for example:  https://grimoire.domain.net

**Comment by Famku** [comment]
I saw that you changed the env.docker file and tried it again.

But the pocketbase container still get the error message:

Connecting to localhost:8090 (127.0.0.1:8090) wget: can't connect to remote host (127.0.0.1): Connection refused

**Comment by goniszewski** [comment]
Please keep in mind that the `.env.docker` file is not used anymore.

I know it's not easy to successfully deploy the app with a custom domain, and it is something that needs to be improved soon. Currently, you need to make sure that your PocketBase container is publicly exposed. The `PUBLIC_POCKETBASE_URL` variable has to hold the value of PB's public URL (e.g., `https://grimoire.mydomain.com:8089`) and `ORIGIN` the public URL of the deployed app (e.g., `https://grimoire.mydomain.com`).

There is [an issue](https://github.com/goniszewski/grimoire/issues/28) with the idea of proxying PB file API calls through the app itself. It will potentially simplify the configurations and remove some gotchas (but can lock you from accessing PB's admin page), so I will explore this as part of the solution.

**Comment by jovobe** [comment]
I'm a bit confused by the docker setup. Do I really need to clone the repository for the containers to work? The normal setup flow would just require to pull docker images, right? But I can't find e.g. the pb_migrations inside the [official image](https://hub.docker.com/r/goniszewski/grimoire).

**Comment by goniszewski** [comment]
Hello @jovobe! A minimalist setup requires at least:
* `docker-compose.yml`
* `.env`
* `pb_migrations/`

I know it would be great to just require the first two (or even the compose file only), but it will force us to provide our personalized PocketBase image. During this stage of development, I would like to fix as many errors as possible and focus on delivering the promised QoL features.
