### ISSUE TITLE
Can't get it working properly in Docker with the Compose

### ISSUE THREAD

**Issue by ArcticFox037** [goniszewski/grimoire#143]
**Describe the bug**
Following the instruction listed on Github, I can't seem to get it to work; registration is non-functioning, and I can't seem to login to anything, despite the fact that the wording suggests it should be usable right away without even a login. The Docker Hub instructions are also not helpful for finding a solution, since one of the of the instructions is to 'set up a root user in the .env'; the required Environment Variables are not listed anywhere for this. I found them in an older issue, but still don't seem to work.

**To Reproduce**
1. Follow Docker-compose.yml installation steps from Github front page

**Expected behavior**
Functioning Grimoire

**Comment by Sparkenstein** [comment]
Most likely it's the error handling, I tried it, if password is say less than 8 chars the BE throws error but  FE doesn't handle it.
If you are good with browsers console or network tab, check for response errors that helped me

**Comment by goniszewski** [comment]
Hello @ArcticFox037 and @Sparkenstein!

Nice catch! I will address this issue in the next update.

**Comment by Sparkenstein** [comment]
Mind if I take a stab at it? I am interested in contributing

**Comment by goniszewski** [comment]
Not at all! All help is greatly appreciated :)

**Comment by Sparkenstein** [comment]
Pushed login/signup error handling, let me know if you need any changes
