### ISSUE TITLE
[Bug] "email" must be a valid email

### ISSUE THREAD

**Issue by rllola** [goniszewski/grimoire#160]
**Describe the bug**
The signup form doesnt allow for my email

**To Reproduce**
1. Go to signup
2. Enter as email : 'me@evil.corp'
3. Click on signup

**Expected behavior**
To accept my totally valid email.

**Screenshots**
![Screenshot from 2024-12-16 19-47-22](https://github.com/user-attachments/assets/30412924-c2fe-4fcb-9005-ef2167fc974e)

**Comment by goniszewski** [comment]
Hello @rllola!

Nice two bugs you found there :) This is probably the issue with the regex we use in the API handler. I'll look into it.

**Comment by goniszewski** [comment]
So, I did check it and the error comes from Joi - our form validation library. As the `.corp` is [not a valid TLD](https://icannwiki.org/.corp), it's being rejected.

For the sake of future proofing the app, a valid email address is expected.
