### ISSUE TITLE
Support internal pocketbase-images

### ISSUE THREAD

**Issue by tamaskan** [goniszewski/grimoire#28]
For docker-internal pocketbase-installations without a public domain some kind of proxy would be useful to avoid missing images.

**Comment by goniszewski** [comment]
Hello @tamaskan! I don't say no, but at the same time I don't have any plans for shipping integrated proxy.

However, if you have some experience configuring Caddy, Nginx, or any other solution to work this way, I would be more than eager to discuss how to expand the documentation with the necessary steps and configurations.

**Comment by goniszewski** [comment]
The app will now proxy PocketBase API calls (including fetching the images) through `/internal` route: [#48](https://github.com/goniszewski/grimoire/pull/48)
