### ISSUE TITLE
support sqlite？

### ISSUE THREAD

**Issue by bestruirui** [goniszewski/grimoire#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by goniszewski** [comment]
Hello @bestruirui! SQLite is used by PocketBase which, in turn, is already deployed with Grimoire.

**Comment by bestruirui** [comment]
I mean grimoire+sqlite not grimoire+PocketBase 🌹

**Comment by goniszewski** [comment]
What would be the benefits of such configuration?

**Comment by bestruirui** [comment]
Only one container is enough, there is no need for a separate PocketBase backend, and the environment variable part, which I set up for a long time when I deployed it myself, is the address part of the backend frontend

**Comment by goniszewski** [comment]
To ditch PB, we would have to write our own auth services, permissions, file storage solution, and backup service and make them at least somewhat secure. And it still has more to offer.

PocketBase is a great piece of software, and I won't just resign from it without a really good reason.

**Comment by bestruirui** [comment]
Thank you for your reply. I see.
