### ISSUE TITLE
Feature: allow disabling registration

### ISSUE THREAD

**Issue by babariviere** [goniszewski/grimoire#31]
**Is your feature request related to a problem? Please describe.**
I would like to use my grimoire instance as a single user one. This would allow me to expose it to the internet without having random people create user on this instance.

**Describe the solution you'd like**
The best solution would be to set an environment variable to enable registration or not (e.g. Gitea does it this way: https://docs.gitea.com/next/administration/config-cheat-sheet#service-service `DISABLE_REGISTRATION`).

**Describe alternatives you've considered**
One hacky way was to do it using this solution:
https://github.com/pocketbase/pocketbase/discussions/3488#discussioncomment-7243287

**Additional context**

**Comment by goniszewski** [comment]
I was planning to add it along with other much-needed configurations to the admin panel. But for such a crucial option, the proposed env option should be better. I will add it ASAP!
