### ISSUE TITLE
Error with .env file

### ISSUE THREAD

**Issue by moraleseder1** [goniszewski/grimoire#36]
**Describe the bug**
Error regarding .env file

**To Reproduce**
Here is my compose file

version: '3.7'
services:
  pocketbase:
    image: spectado/pocketbase:0.19.2
    container_name: grimoire-pocketbase
    restart: unless-stopped
    ports:
      - '8091:80'
    volumes:
      - /mnt/user/appdata/grimoire/pb_data:/pb_data
      - /mnt/user/appdata/grimoire/pb_migrations:/pb_migrations/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8091/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
  grimoire:
    image: goniszewski/grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - pocketbase

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser Edge
 - Version [

**Additional context**
I'm trying to deploy this using portainer but I get this error message

Deployment error
failed to deploy a stack: Failed to load /data/compose/47/.env: open /data/compose/47/.env: no such file or directory

**Comment by goniszewski** [comment]
Hello @moraleseder1! The Compose is looking for `.env` file and is unable to do so in the working directory.

You can always go to `Stacks > Add stack` in Portainer. Then place the contents of `docker-compose.yml` into the web editor while removing `env_file: .env` part for `pocketbase` and `grimoire` services. After this part, you can just add your env variables in the _Environment variables_ section, review all input, and press the _Deploy the stack_ button.

**Comment by moraleseder1** [comment]
Hi @goniszewski and thank  you for your response and I apologize ahead of time since I am very new to docker compose. Is this what you mean?

version: '3.7'
services:
  pocketbase:
    image: spectado/pocketbase:0.19.2
    container_name: grimoire-pocketbase
    restart: unless-stopped
    ports:
      - '8190:80'
    volumes:
      - /mnt/user/appdata/grimoire/pb_data:/pb_data
      - /mnt/user/appdata/grimoire/pb_migrations:/pb_migrations/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8190/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    #env_file: .env
  grimoire:
    image: goniszewski/grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    #env_file: .env
    environment:
       - PUBLIC_POCKETBASE_URL: http://192.168.1.33:8090
       - ROOT_ADMIN_EMAIL: eder.morales16@gmail.com
       - ROOT_ADMIN_PASSWORD: 1313541616
       - ORIGIN: http://192.168.1.33:5173
       - PUBLIC_HTTPS_ONLY: false
       - PORT: 5173
       - PUBLIC_SIGNUP_DISABLED: false
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '27328:27328'
    depends_on:
      - pocketbase

**Comment by goniszewski** [comment]
Yes, it should work. For the future, please use the code tag as it will help us reading your code.
