### ISSUE TITLE
No way to choose model in Ollama

### ISSUE THREAD

**Issue by SoiledBrush** [goniszewski/grimoire#37]
There is nothing to choose in model dropdown

![Screenshot from 2023-12-09 12-14-56](https://github.com/goniszewski/grimoire/assets/43366389/d4a46866-c778-4b3b-bfad-dc841311205d)
 ```
curl http://10.0.0.76:11434/
Ollama is running%  
```                                              

I am not sure if ollama is expected to be working in current release.
If not, you can close the issue.

**Comment by goniszewski** [comment]
Hello @SoiledBrush! Integration with Ollama is an early preview. Nonetheless, it should fetch the tags of models available locally.

I have just tested it on a fresh Grimoire + Ollama installation, and it works just fine. Please keep in mind, that you need to press the _TEST_ button to make a first call to Ollama's API.

<img width="501" alt="Screenshot 2023-12-10 at 12 41 01" src="https://github.com/goniszewski/grimoire/assets/43510122/fec7c842-189c-4499-8409-24189b392489">

**Comment by SoiledBrush** [comment]
![image](https://github.com/goniszewski/grimoire/assets/43366389/a8eb8478-3e55-4653-93c0-d7ead55b0595)

Ok, test buttons works if I start grimoire on the local machine. But doesn't work if I run it in on my "homelab".
Maybe it has something to do with the fact that I changed ORIGIN=http://localhost:5173 to http://10.0.0.254:5173 to avoid "cross-site form submissions forbidden" error.

**Comment by goniszewski** [comment]
You probably should configure Ollama to accept incoming request from Grimoire's origin. Please refer to this document for more information: https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network

**Comment by SoiledBrush** [comment]
```
cat /etc/systemd/system/ollama.service.d/environment.conf     
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
```
I already have that set up.

**Comment by goniszewski** [comment]
Ok, I see. I don't know what's the exact origin of the request that comes from Grimoire. The call to Ollama API is made on the client-side, so you can check the response for it in the _Network_ tab in your browser.

**Comment by goniszewski** [comment]
It should be now fully resolved with the fixes/improvements made for https://github.com/goniszewski/grimoire/issues/71.
