### ISSUE TITLE
Grimoire web app is showing outdated information for Settings and Bookmarks

### ISSUE THREAD

**Issue by KevinXZX** [goniszewski/grimoire#40]
**Describe the bug**
After deleting a bookmark or changing settings, the webapp does not update the view until the page is refreshed. 

**To Reproduce**
1. Go to settings, toggle animations off.
2. Click on the "Back to Home" button
3. Go back to settings, animations are still toggled on
4.  Refresh the page, animations are now toggled off.
5. Similarly after deleting a bookmark, it is still present on the view until the page is refreshed.

**Expected behavior**
The webapp should have the latest data. You should not have to refresh to see the up to data settings or bookmarks.

**Screenshots**
Before refresh:
![image](https://github.com/goniszewski/grimoire/assets/72686328/7d90bb2f-5a0a-4fe2-943e-d53fc2c05ef1)
After refresh: 
![image](https://github.com/goniszewski/grimoire/assets/72686328/ada47d82-32f7-4b9f-a7e2-03a4ec3023a1)

**Desktop (please complete the following information):**
 - OS: Windows 11, Grimoire running on WSL
 - Browser Firefox
 - Version 120.0.1

Let me know if you need any more information

**Comment by goniszewski** [comment]
Hello @KevinXZX! Thank you for this great first issue :) 

The state's management isn't functioning properly, which is the source of the issues you mentioned. I am aware (of most?) of them and will work towards fixing it.

**Comment by goniszewski** [comment]
Hi again @KevinXZX. Please check if the latest version fixes this issue for you.

**Comment by gebi** [comment]
just found the same problem, deleting a bookmark requires sometimes multiple delete clicks to show the green 'bookmark deleted in the lower middle" and after that requires a reload to take effect (show the bookmark as deleted)
