### ISSUE TITLE
Can't build the application

### ISSUE THREAD

**Issue by banphi** [goniszewski/grimoire#53]
Hi,
i'm trying to build the docker-compose but i t fail in the JS stacktrace, if i understand correctly.

This is the list of messages:

> Building grimoire
[+] Building 285.0s (13/15)                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 1.04kB                                                                         0.0s
 => [internal] load metadata for docker.io/library/node:20-slim                                                0.0s
 => [internal] load .dockerignore                                                                              0.0s
 => => transferring context: 273B                                                                              0.0s
 => [base 1/5] FROM docker.io/library/node:20-slim                                                             0.0s
 => [internal] load build context                                                                              0.1s
 => => transferring context: 10.52kB                                                                           0.1s
 => CACHED [base 2/5] RUN corepack enable                                                                      0.0s
 => CACHED [base 3/5] RUN apt-get update && apt-get install -y python3 python3-pip                             0.0s
 => CACHED [base 4/5] COPY . /app                                                                              0.0s
 => CACHED [base 5/5] WORKDIR /app                                                                             0.0s
 => CACHED [build 1/2] RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile        0.0s
 => CACHED [prod-deps 1/1] RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-loc  0.0s 
 => CACHED [stage-3 1/3] COPY --from=prod-deps /app/node_modules /app/node_modules                             0.0s
 => ERROR [build 2/2] RUN pnpm run build                                                                     284.7s
------                                                                                                              
 > [build 2/2] RUN pnpm run build:                                                                                  
2.117                                                                                                               
2.117 > grimoire@0.2.2 build /app                                                                                   
2.117 > vite build                                                                                                  
2.117                                                                                                               
5.613 
5.615 vite v4.5.1 building SSR bundle for production...
5.694 transforming...
9.906 
9.906 warn - As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.
9.906 warn - Remove it from the `plugins` array in your configuration to eliminate this warning.
10.85 
10.85 ╭── 🌼 daisyUI 3.9.4 https://daisyui.com
11.18 │
11.18 ├── 2 themes are enabled. How to add more themes:
11.18 │   https://daisyui.com/docs/themes
11.18 │
11.18 ╰── 💚 Support daisyUI project: https://opencollective.com/daisyui
11.18 
11.77 
11.77 ╭── 🌼 daisyUI 3.9.4 https://daisyui.com
12.04 │
12.04 ├── 2 themes are enabled. How to add more themes:
12.04 │   https://daisyui.com/docs/themes
12.04 │
12.04 ╰── ⭐ Star daisyUI project on GitHub: https://github.com/saadeghi/daisyui
12.04 
64.97 src/routes/+page.svelte (189:13) "PUBLIC_SIGNUP_DISABLED" is not exported by "virtual:$env/static/public", imported by "src/routes/+page.svelte".
66.19 "BaseAuthStore" is imported from external module "pocketbase" but never used in "src/lib/pb.ts".
66.20 ✓ 5036 modules transformed.
66.63 rendering chunks...
72.59 vite v4.5.1 building for production...
72.59 
72.61 transforming...
283.8 
283.8 <--- Last few GCs --->
283.8 
283.8 [19:0x560ebd0]   276977 ms: Mark-Compact 1836.5 (1906.5) -> 1821.3 (1908.3) MB, 1863.04 / 0.21 ms  (average mu = 0.207, current mu = 0.212) allocation failure; scavenge might not succeed
283.8 [19:0x560ebd0]   279277 ms: Mark-Compact 1838.0 (1908.3) -> 1822.5 (1909.8) MB, 1995.94 / 0.06 ms  (average mu = 0.171, current mu = 0.132) allocation failure; scavenge might not succeed
283.8 
283.8 
283.8 <--- JS stacktrace --->
283.8 
283.8 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
283.8 ----- Native stack trace -----
283.8 
283.8  1: 0xca5430 node::Abort() [node]
283.8  2: 0xb7807d  [node]
283.8  3: 0xeca0b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
283.8  4: 0xeca397 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
283.8  5: 0x10dc0e5  [node]
283.8  6: 0x10dc674 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
283.8  7: 0x10f3564 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [node]
283.8  8: 0x10f3d7c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
283.8  9: 0x114cb3c v8::internal::MinorGCJob::Task::RunInternal() [node]
283.9 10: 0xd201a6  [node]
283.9 11: 0xd22d5f node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
283.9 12: 0x188aa33  [node]
283.9 13: 0x189f41b  [node]
283.9 14: 0x188b757 uv_run [node]
283.9 15: 0xbbbb83 node::SpinEventLoopInternal(node::Environment*) [node]
283.9 16: 0xcf4d25  [node]
283.9 17: 0xcf56ed node::NodeMainInstance::Run() [node]
283.9 18: 0xc5f367 node::Start(int, char**) [node]
283.9 19: 0x7f751e2171ca  [/lib/x86_64-linux-gnu/libc.so.6]
283.9 20: 0x7f751e217285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
283.9 21: 0xbb8d7e _start [node]
284.5 Aborted (core dumped)
284.5  ELIFECYCLE  Command failed with exit code 134.

> Dockerfile:14

>  12 |     FROM base AS build
  13 |     RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
  14 | >>> RUN pnpm run build
  15 |     
  16 |     FROM base

> ERROR: failed to solve: process "/bin/sh -c pnpm run build" did not complete successfully: exit code: 1
ERROR: Service 'grimoire' failed to build : Build failed

Are a minimal requirements to install?
I have 4GB of memory in the system but i use less than 1GB.
I hope that someone can help me.

 - OS: Ubuntu 22.04.3 LTS x86_64 
 - Browser Firefox
 - Version 121.0

**Comment by goniszewski** [comment]
Hello @banphi! Hello @banphi! Yes, the building process takes a lot of memory. Currently, the image is only being built with ARM in mind. I hope I will have time soon to address that and add support for x86_64 as well.

**Comment by banphi** [comment]
> Hello @banphi! Yes, the building process takes a lot of memory. Currently, the image is only being built with ARM in mind. I hope I will have time soon to address that and add support for x86_64 as well.

Thank you for your reply.
i solved with a workaround: i build the docker-compose on a better machine, with more ram, and then copy Docker image from one machine to another.
