### ISSUE TITLE
Docker image without needing source

### ISSUE THREAD

**Issue by laurentlbm** [goniszewski/grimoire#7]
In order to simplify installation, it would be great to be able to use the docker image without needing to clone the repository. Ideally, the image would also include and apply all the pocketbase migrations at startup, so that those files aren't required either.

**Comment by balub** [comment]
I'd like to work on this if possible.

**Comment by goniszewski** [comment]
Thanks @balub ! It would be great if we could use GH Actions to automate the deployment after each release & merge to `main`.

**Comment by goniszewski** [comment]
I have used a simple GitHub Action to automatically new `goniszewski/grimoire:latest` image after every push to `main` branch: https://github.com/goniszewski/grimoire/commit/e8a47a64305170bf963d01dfb82803066a2068a0

Sorry @balub for not informing you, but I wanted to introduce it ASAP. I hope it's ok with you!
