### ISSUE TITLE
Trying to add a bookmark without a category triggers an error

### ISSUE THREAD

**Issue by c157fl** [goniszewski/grimoire#72]
Hi there,

### **Describe the bug**
Trying to add a bookmark without any category existing triggers an error and blocks the adding process.

### **To Reproduce**
1. Steps to reproduce the behavior:
2. Delete all categories
3. Open browser dev tools
4. Try to add a bookmark
5. See error and process locking

### **Expected behavior**
Display an error saying that no category exists/create a "Uncategorized" category/Allow the creation of the category on the pane

### **Screenshots**
![image](https://github.com/goniszewski/grimoire/assets/108611247/ec6811c2-236f-4830-ae87-d0f14097bb3a)

**Comment by goniszewski** [comment]
Hello @c157fl! You shouldn't be able to delete the initial category, only edit it. I will look into it in my spare time.

**Comment by c157fl** [comment]
Hi @goniszewski . Curiously, I did not have an initial category. I'll do a full wipe of everything, try a fresh install later today and report back.

**Comment by c157fl** [comment]
Did a complete reset and effectively the _Uncategorized_ category was created.
Seems that it was an issue with my installation.
Apologies for the inconvenience.
