### ISSUE TITLE
Top-level category does not show all bookmarks under subcategories or the subcategories of those subcategories.

### ISSUE THREAD

**Issue by nothing2obvi** [goniszewski/grimoire#77]
**Describe the bug**
I have a bookmark under Self-Hosted > Photos and another one under Self-Hosted > Bookmarks. Clicking on Self-Hosted does not list any of those bookmarks.

**To Reproduce**
1. Create bookmarks at category level: Self-Hosted > Photos and category level: Self-Hosted > Bookmarks.
2. Click on Self-Hosted
3. See that none of the bookmarks from #1 are listed under Self-Hosted.

**Expected behavior**
Bookmarks from subcategories and also their subcategories should be listed underneath the top-level category.

**Screenshots**
![Screen Shot 2024-03-30 at 11 26 24 AM](https://github.com/goniszewski/grimoire/assets/85228035/b9f79160-2a24-4793-ba31-3f455a78e7c4)
![Screen Shot 2024-03-30 at 11 26 32 AM](https://github.com/goniszewski/grimoire/assets/85228035/c5e3c1b1-4e7d-4430-875f-3ed2da1999ec)

**Desktop (please complete the following information):**
 - OS: [Mac Monterey 12.7.4]
 - Browser [Opera]
 - Version [108.0.5067.29]

**Additional context**
Running latest version (v0.2.6) on Docker Desktop for Mac 4.28.0.

**Comment by goniszewski** [comment]
Hello @nothing2obvi! Thank you for pointing out this issue. I'm aware of most problems and limitations, yet it's always a good thing to underline the most obvious ones.

I will add that to my backlog, same as https://github.com/goniszewski/grimoire/issues/76 🙂

Please give me some time to implement it correctly. I will update you in those issues. Thanks again!

**Comment by nothing2obvi** [comment]
Thanks for your reply. Sounds great!
