### ISSUE TITLE
Internal Proxy Cookies & docker-latest

### ISSUE THREAD

**Issue by tamaskan** [goniszewski/grimoire#80]
According  to https://stackoverflow.com/questions/47870786/express-proxy-api-calls-with-cookie it seems possible to add the cookies from the initial request to the proxy request, therefore enabling cookie-based sso

The :latest seems to point to version 0.26 (probably because of the breaking changes). That should be mentioned

**Comment by goniszewski** [comment]
Hi @tamaskan! Let me look into it shortly. Thank you for spotting this possible improvement.

As for the Docker tags, `0.3.0`, `0.3`, `latest`, and `main` are pointing to the same image at the moment.

**Comment by goniszewski** [comment]
As I can see in the CI log on GitHub, the push to the `main` branch and an actual release fired the workflow separately. Because of the different SHA of those commits, the digest value also differs.:

- https://github.com/goniszewski/grimoire/actions/runs/8493669976
- https://github.com/goniszewski/grimoire/actions/runs/8493674783

**Comment by goniszewski** [comment]
@tamaskan it should be updated automatically, but for some reason wasn't.

I looked into the documentation, and it looks like cookies are always passed to the proxy request. We don't need to overwrite them. Or maybe do you have something different in mind?

**Comment by goniszewski** [comment]
@tamaskan could you review the changes from the linked PR? If yes, it would be great to have your opinion on this implementation!

**Comment by goniszewski** [comment]
Yes, indeed 😄 Fixed!

**Comment by goniszewski** [comment]
@tamaskan the error you're referring to, `heritage yee`, should be now resolved in https://github.com/goniszewski/grimoire/releases/tag/v0.3.3.

**Comment by goniszewski** [comment]
Please upgrade to the latest version of Grimoire. You can use the integrated [migration tool](https://grimoire.pro/docs/migration-tool/) to transfer your data to new format.
