### ISSUE TITLE
Grimoire API not reachable

### ISSUE THREAD

**Issue by vogonwann** [goniszewski/grimoire#85]
**Describe the bug**
Grimoire API not reachable from extension through Cloudflare tunnel or locally on fresh docker setup.
Also, trying to directly add bookmark by accessing grimoire locally is not possible because Add button is disabled and bookmark popup cannot be closed.

**To Reproduce**
1. Setup docker container inside ProxMox Ubuntu 22.04 CT
2. Click on extension button in Firefox
3. Grimoire API is not reachable

**Expected behavior**
Bookmark was saved to Grimoire

**Desktop (please complete the following information):**
 - OS: Nobara 39
 - Browser Firefox
 - Version 124.0.1

**Comment by goniszewski** [comment]
Hello @vogonwann! Are you able to get OK response from `<GRIMOIRE_URL>/api/health` from the same machine you as your browser?

Also, the _Add_ button is disabled if there's no metadata or if it's being fetched. If it lasts more than 3-5s, you can check your browsers dev console to check why it's failing.

**Comment by goniszewski** [comment]
@vogonwann I have discovered that the error is related to the toast library we are using. I'll let you know when there is a fix for it!

**Comment by vogonwann** [comment]
@goniszewski Thanks!

**Comment by goniszewski** [comment]
@vogonwann This error should be now resolved in https://github.com/goniszewski/grimoire/releases/tag/v0.3.3.

If it still persists for you, please reopen this issue!

**Comment by vogonwann** [comment]
@goniszewski Fixed! Thanks a lot!
