### ISSUE TITLE
Add Bookmark and Edit buttons not working

### ISSUE THREAD

**Issue by raquel** [goniszewski/grimoire#89]
**Describe the bug**
The "add bookmark" and "edit" buttons are not working. The first when you click the component to insert the url appears, but the "ADD" button never be enabled. Clicking on edit button do nothing. The delete button and the chrome extension are working fine.

**To Reproduce**
1. Go to 'http://0.0.0.0:5173/'
2. Click on 'add bookmark'
3. Paste the URL on the pop up
4. Add button not enabled

**Expected behavior**
Open another box with the details related to the link that I paste.  

**Desktop (please complete the following information):**
 - OS: Armbian 24.5.0-trunk.417 jammy" based on  Ubuntu 22.04.4
 - Browser: Brave
 - Version  1.64.122

**Additional context**
I use the docker version from source code and updated the code today.
I saw this errors on the developer tools when the page loads. Don't know if this is relevant
![image](https://github.com/goniszewski/grimoire/assets/392029/dd8625bd-3979-4965-8604-5ac4152027ef)

**Comment by goniszewski** [comment]
Resolved with https://github.com/goniszewski/grimoire/releases/tag/v0.3.3.
