### ISSUE TITLE
Website favicon

### ISSUE THREAD

**Issue by corykinney** [goniszewski/grimoire#94]
First, I recently found this project and I'm excited to try this out as a self-hosted bookmark alternative to Raindrop! It's super minor, but I thought I would point out that the grimoire website favicon is the default Docusaurus icon, and I'm sure the intention is to have the grimoire icon there.  But I really I just wanted to take advantage of this to let you know that I appreciate the hard work you're putting into the project that you're graciously allowing others to use!

**Comment by goniszewski** [comment]
Hello @corykinney!

I thought I had it already updated, but maybe I need to take a second look at this. Thank you for bringing it to me and I hope you will find Grimoire useful!

PS, Sorry for not getting back to you sooner!

**Comment by goniszewski** [comment]
Fixed it. Thanks again @corykinney!
